### ISSUE TITLE
Feature request: Add world whitelist/blacklist

### ISSUE THREAD

**Issue by SlimeDog** [foncused/ExplosionRegeneration#1]
Spigot 1.13.2 latest
ExplosionRegeneration 1.3.2

Please add configuration and support for world list in which ER is enabled (whitelist) or disabled (blacklist). Either is sufficient, or both if you feel the need.

**Comment by foncused** [comment]
Added silently in version 1.3.5 of the plugin.

**Comment by SlimeDog** [comment]
Thanks. Much appreciated.

I will return to testing ER when WG fixes regions TNT protection (or explains what I have misconfigured).
