### ISSUE TITLE
Honor WorldGuard TNT restrictions

### ISSUE THREAD

**Issue by SlimeDog** [foncused/ExplosionRegeneration#2]
Spigot 1.13.2 latest
ExplosionRegeneration 1.3.3

WorldGuard/.../config.yml includes:
```
ignition:
    block-tnt: false
    block-tnt-block-damage: true
```
With ExplosionRegeneration disabled, TNT explosions cause no damage. With ExplosionRegeneration enabled, TNT explosions cause block damage (and then regenerate the damaged blocks). It seems to me that ExplosionRegeneration should honor WorldGuard protections.

**Comment by foncused** [comment]
This should be resolved in the next version (1.3.5). I will leave this open in case it is not resolved - thanks for testing for me.

**Comment by foncused** [comment]
FYI when I added WorldGuard support, I wrote it against an older version. Didn't realize 7 was out - repo is now updated, but I have yet to update the .jar on Spigot. Will need to test before doing that. :)

**Comment by SlimeDog** [comment]
It's a bit problematic. WG keeps changing the API, which has disastrous effects on some plugins (maybe not ER). So everything becomes very version-sensitive. :(

**Comment by foncused** [comment]
This can probably be closed. As far as I can tell, from my testing, ExplosionRegeneration now supports WorldGuard 7.0.0 for 1.13.2!

**Comment by SlimeDog** [comment]
I'm not currently using ER. I'll try to configure a test server and give it a whirl.
