### ISSUE TITLE
New option no sound

### ISSUE THREAD

**Issue by Skyexir** [foncused/ExplosionRegeneration#3]
(sorry I didn't manage to create a pull request)

Hello, i really love your plugin!
Can you add an option to disable the sound please (like putting NONE in place of ENTITY_CHICKEN_EGG) ? :)

**Comment by foncused** [comment]
Seems logical enough, I'll add a toggle for both the particles and the sound.

**Comment by foncused** [comment]
Added in version 1.3.9, feel free to update and set the config options to an empty string ("") if you want the particle/sound effects disabled.
