### ISSUE TITLE
tnt regen

### ISSUE THREAD

**Issue by Envel-Nikita-Gutsenkov** [foncused/ExplosionRegeneration#8]
unfortunately, I could not disable the rollback of all other mobs, except for creepers. blocks do not drop out and are restored even after tnt

**Comment by foncused** [comment]
Not sure what you mean about rolling back mobs. Can you elaborate?

There is configuration for item drops, check here: https://github.com/foncused/ExplosionRegeneration/blob/master/src/main/resources/config.yml
